language: python

python:
  - "2.7"

sudo: true

# command to install dependencies
before_install: 
- sudo pip install --upgrade pip
- sudo apt-get -y build-dep python-imaging
- sudo apt-get install -y libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
- sudo pip install Pillow
- echo "573e18dfcf2ca4807aa0e428cd419fcb" > api.key

# specify os
os:
- linux

# configure which branches to run
branches:
  # whitelist
  only:
    - master
    - devel

# command to run unit tests
script:
- python WeatherPrinter.py
